### ISSUE TITLE
Is a point set also known as general topology?

### ISSUE THREAD

**Issue by dorian-hart-ferrer** [gjf2a/point_set#1]
Hi, I found this wikipedia article about general topology.  Is this a good place to start learning about point set data structures?  Thanks, neat project idea!

https://en.wikipedia.org/wiki/General_topology

**Comment by gjf2a** [comment]
Hi Dorian,

I created this data structure as part of a (failed) attempt to solve Part 2 of [this puzzle](https://adventofcode.com/2023/day/21). I wanted to be able to quickly check whether a particular 2D point had already been visited. This is essentially a super-fast hash set for such points.

I didn't really have topology in mind when I created it. The Wikipedia article gives a good overview. If you have deeper questions about the topic, I don't really know much about it, but I know people who do, and I could talk to them to get you some pointers.

Thanks for the comment!

Uncle Gabe

**Comment by dorian-hart-ferrer** [comment]
Oh cool!

I am interested in contributing to some open source projects, so I thought I'd poke around this one you created recently.

Is this a project that I could help with?  If not, are there any other projects you are working on that I could help with?

Thanks!  Hope all is well.

Dorian.
